# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  leefstijlcoaching.nl:
    site_hosts:
      - canonical: leefstijlcoaching.nl
        redirects:
          - www.leefstijlcoaching.nl
      - canonical: leefstijlcoaching.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: matthijs@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
